name: Build and Push Firecrawl Images

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set owner lowercase
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ env.OWNER }}/firecrawl:latest

  build-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set owner lowercase
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Playwright image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/playwright-service-ts
          file: ./apps/playwright-service-ts/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ env.OWNER }}/firecrawl-playwright:latest
